### ISSUE TITLE
[intellivoid] Add support for Spam Protection Lookup API

### ISSUE THREAD

**Issue by ajhalili2006** [AnimeKaizoku/SaitamaRobot#186]
> **This issue is currently WIP, stay tuned for updates.** Currently, I'm drafting this issue and I submitted it, just to avoid losing my work while watching the [Doors 5 premiere (sorry, I just watching the replay)](https://www.twitch.tv/videos/718310745).

## Related Resources

The Spam Protection V2 changelog: https://t.me/Intellivoid/328

Lookup API Documentation: https://docs.intellivoid.net/spamprotection/v1/lookup

**Comment by TsunayoshiSawada** [comment]
As we are handling our own issues with increasing load (among other shit), this wont be considered anytime soon. 
Will leave the issue opened up as a future reminder of sorts.

**Comment by TsunayoshiSawada** [comment]
This probably wont be added anytime soon.

**Comment by ajhalili2006** [comment]
> This probably wont be added anytime soon.

Sed, why?

**Comment by TsunayoshiSawada** [comment]
Cause noone is willing to write fresh modules rn
