### ISSUE TITLE
Minor typo, priority: low

### ISSUE THREAD

**Issue by andy866** [AnimeKaizoku/SaitamaRobot#198]
here are two typos found in markdownhelp:
https://github.com/AnimeKaizoku/SaitamaRobot/blob/adc948eb6ce903ff1abe90728cca504e898b8374/SaitamaRobot/modules/misc.py#L21 
where the markdown `*:*` isn't working there. And it looks weird if the colon is bold.
https://github.com/AnimeKaizoku/SaitamaRobot/blob/adc948eb6ce903ff1abe90728cca504e898b8374/SaitamaRobot/modules/misc.py#L26
where "Example" appeared 3 times

**Comment by TsunayoshiSawada** [comment]
Corrected, thanks for pointing these out and for the detailed explanation/content highlighting. 
Future note: You are free to directly open pull requests on the :shiken branch, we are always open to suggestions and corrections.
