### ISSUE TITLE
Enhancement: Bot Reply to /runs Shouldn't be Roast

### ISSUE THREAD

**Issue by successful-fella** [AnimeKaizoku/SaitamaRobot#21]
Replies like:
- A long time ago, in a galaxy far far away... Someone would've cared about that. Not anymore though.
- Is that all you've got?

takes away all the fun.

Though replies like:
- And they disappeared forever, never to be seen again.
- Ah, what a waste. I liked that one.

are more fun.

Thanks for reading. I hope this will be considered.

**Comment by TsunayoshiSawada** [comment]
You can edit the file https://github.com/AnimeKaizoku/SaitamaRobot/edit/shiken/tg_bot/modules/fun_strings.py

And remove the bad ones or add fun ones and commit with a title and explanation of what you did. 
Then click open pull request. 

We will review and merge to shiken(dev) branch, this is then pulled into master version after some time.

**Comment by Dank-del** [comment]
@TsunayoshiSawada Okay

**Comment by successful-fella** [comment]
@TsunayoshiSawada Okay, thanks for considering.
