### ISSUE TITLE
No app.json located in the repo URL provided

### ISSUE THREAD

**Issue by ghost** [AnimeKaizoku/SaitamaRobot#262]
![Screenshot_2020-10-22-04-04-38-480_com cloudmosa puffinFree](https://user-images.githubusercontent.com/68055360/96794433-d2e7a100-141b-11eb-86e6-75521bdec472.jpg)
![Screenshot_2020-10-22-04-05-08-371_com cloudmosa puffinFree](https://user-images.githubusercontent.com/68055360/96794461-df6bf980-141b-11eb-881d-e2a0ecaec85d.jpg)

**I wanted to ask that...**
Just type your question here [.can u find the error ? .]
i just forked your codes and edited in my way . with a name only . balence codes are not changed till now . but , the deployment time , in heroku shown a message as "No app.json located in the repo URL provided"
but file have in there . i can show my evidences and 
i can share my app"s url ,pls check and help to solve the problem

my repo url : https://github.com/sakhaavvaavaj93/saithan_Robot.git

and pls checkout the attached document
![Screenshot_2020-10-22-00-35-24-414_com cloudmosa puffinFree](https://user-images.githubusercontent.com/68055360/96794131-44731f80-141b-11eb-84ed-1db9573c1fe6.jpg)

and pls checkout the attached document[]() 
![Uploading Screenshot_2020-10-22-00-35-24-414_com.cloudmosa.puffinFree.

**Comment by sppidy** [comment]
Clearly Mentioned in Readme.md No Forks are Supported

**Comment by TsunayoshiSawada** [comment]
![image](https://user-images.githubusercontent.com/34431649/97075110-dd15c500-15fe-11eb-8f29-a71d8086c126.png)
You pushed all files again as your own, squashing over 2000 commits into 80
Making a mess when it comes to finding out who pushed what code and why. 

A part of gpl license isnt just to keep the repo open sourced, it is also to carry over the commit history and then push your own edits over it. 
Sorry, wont assist your repo on this.
Fair support requires fair play on your end.
