### ISSUE TITLE
Https Markdown On Welcome Message Is Bugged

### ISSUE THREAD

**Issue by FristyFlakes** [AnimeKaizoku/SaitamaRobot#265]
Below Is A ScreenShot Of How The Bug Looks Like When I Input A Welcome Message With [Rules](https://t.me/anything) it gives a weird bug to the welcome message

![Screenshot_20201030_063651](https://user-images.githubusercontent.com/71187213/97663830-9dc1fb00-1a7a-11eb-954e-66b44e395758.png)

**Comment by Tusharpalx** [comment]
Format is wrong.
Is use in The end of message no there. For more info see /welcomehelp conmmand

**Comment by FristyFlakes** [comment]
Format is indeed correct and works for all other robots i send this command. You can try making a hyperlink in your welcome message to understand what I'm trying to explain

**Comment by TsunayoshiSawada** [comment]
Please join us at https://t.me/OnePunchDev to test/play around with this.

**Comment by FristyFlakes** [comment]
Works fine with normal font characters i guess the font added to it caused the distortion.  Thanks for your time
