### ISSUE TITLE
@starryboi ke dum pe chalta hai Saitama ko 

### ISSUE THREAD

**Issue by D3IGUVICK7IIK** [AnimeKaizoku/SaitamaRobot#320]
apna loda apni maa ko deta jake beta chutiye madrchod tu case solve krne ka 500 lega teri mako bhej ese hi 2000 de dunga or tere jesa dusra peda ho jayega

**Comment by TsunayoshiSawada** [comment]
Oh, im madarchod? so your mom told you about huh, sad.
Come back when you have learned how to abuse without becoming a meme. 

Gawar
