### ISSUE TITLE
[welcome] Do not give welcome mute to gbanned users, only ban notice. 

### ISSUE THREAD

**Issue by TsunayoshiSawada** [AnimeKaizoku/SaitamaRobot#357]
**Is your feature request related to a problem? Please describe.**
Welcome mute shows a welcome mute/welcome message to a gbanned user and follows it with a gban alert. 

**Describe the solution you'd like**
Do not show welcome mute or custom welcome for gbanned/spamwatched ones. 
Just their ban notice

**Comment by TsunayoshiSawada** [comment]
test

**Comment by TsunayoshiSawada** [comment]
test

**Comment by Neppu-Nep** [comment]
Should be fixed in - aacd066850b6598b8d943ce6345264bc84192fcf
