### ISSUE TITLE
/demote doesnt work on bots that Saitama promoted

### ISSUE THREAD

**Issue by TsunayoshiSawada** [AnimeKaizoku/SaitamaRobot#358]
**Describe the bug**
When Saitama promotes a bot, it cant demote it back.
Even when Saitama is the bot that promoted it. 

Happens when the target is a bot

**To Reproduce**
Promote a bot using saitama 
Try to demote it 
Bot wont demote and saitama will deny to recognise the bot

**Comment by DragSama** [comment]
Bots can't demote other bots

**Comment by TsunayoshiSawada** [comment]
Btw, we should add something to this. 
Like if Saitama promotes a bot give a notice and a button to confirm promoting a bot.
