### ISSUE TITLE
[log channel] When you add a bot to a group the log channel shows that you joined the group, instead of the bot

### ISSUE THREAD

**Issue by TsunayoshiSawada** [AnimeKaizoku/SaitamaRobot#359]
**Describe the bug**
When you add a bot to a group the log channel shows that you joined the group, instead of the bot

**To Reproduce**
Just setup log channel
Add a bot to group 
Log will say as shown in screenshot

**Expected behavior**
It should show that you added a bot

**Screenshots(if any)**
![image](https://user-images.githubusercontent.com/34431649/106234969-c1364680-621f-11eb-859b-efc52f7b2273.png)

**Comment by Neppu-Nep** [comment]
Should be fixed in - aacd066850b6598b8d943ce6345264bc84192fcf
