### ISSUE TITLE
Do not log AI disabled/enabled on global logs channel

### ISSUE THREAD

**Issue by TsunayoshiSawada** [AnimeKaizoku/SaitamaRobot#361]
Do not log the AI DISABLED/ENABLED on global logs

![image](https://user-images.githubusercontent.com/34431649/106235481-c1831180-6220-11eb-92de-70c4e1fbe9b0.png)

**Comment by Neppu-Nep** [comment]
Fixed in - 403967a5d97c1fd8a6ab34889d6de06c512008ff
