### ISSUE TITLE
Triggered filter reply and /rules reply point to the user who ran command even when the user is replying to someone

### ISSUE THREAD

**Issue by TsunayoshiSawada** [AnimeKaizoku/SaitamaRobot#362]
**Describe the bug**
The response of these 2, if a user is replying to another user with the command should also reply to the targeted user. 

**Screenshots(if any)**
![image](https://user-images.githubusercontent.com/34431649/106246695-838fe880-6234-11eb-863a-678bb54d6a90.png)

**Comment by Neppu-Nep** [comment]
Removed filter replying in - 1d023be36e1a4208179cf4631788b5b7ad605238
