### ISSUE TITLE
pyrate-limiter not valit

### ISSUE THREAD

**Issue by NetSHELL-Team** [AnimeKaizoku/SaitamaRobot#368]
Using cached https://files.pythonhosted.org/packages/f8/89/c9ab40530fb9142890a79bf39b6f2ee47c311729358794719acd15974e68/alphabet-detector-0.0.7.tar.gz
Collecting pyrate-limiter (from -r requirements.txt (line 31))
  Could not find a version that satisfies the requirement pyrate-limiter (from -r requirements.txt (line 31)) (from versions: )
No matching distribution found for pyrate-limiter (from -r requirements.txt (line 31))

requirements pyrate-limiter
centos7

**Comment by DragSama** [comment]
Sounds like a problem with your pip installation or the way you are installing requirements because pyrate-limiter is definitely on PyPi
