### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by NetSHELL-Team** [AnimeKaizoku/SaitamaRobot#369]
creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/psutil
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=580 -DPSUTIL_LINUX=1 -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8msg74w8/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mak6ttru-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-8msg74w8/psutil/

isseu run pip3 install -r requirements.txt

**Comment by starry-shivam** [comment]
As you can see you haven't properly installed the header files for python dev in order for psutil to compile it's C bindings. Install it with:
`sudo apt-get install python3-dev`

**Comment by NetSHELL-Team** [comment]
not work & more others problem

**Comment by starry-shivam** [comment]
> not work & more others problem

[Click here](https://www.google.com/search?q=fatal%20error%3A%20Python.h%3A%20No%20such%20file%20or%20directory%0A%23include%20%3CPython.h%3E&ie=utf-8&oe=utf-8&client=firefox-b-m) to learn how to google the errors, also this isn't saitama's issue but the problem with your environment...

And iirc we don't provide support for forks these days anyway

**Comment by NetSHELL-Team** [comment]
__init__.py", line 193, in <module>
    updater = tg.Updater(TOKEN, workers=WORKERS, use_context=True)
TypeError: __init__() got an unexpected keyword argument 'use_context'

what is this (^_^)

**Comment by starry-shivam** [comment]
Again it's your environment's problem not saitama's, you've PTB v11.1 installed on your system and saitama uses [12.8](https://github.com/AnimeKaizoku/SaitamaRobot/blob/15d9e5710a329c5325dfc46f05bbd01c30987715/requirements.txt#L7)

**Comment by NetSHELL-Team** [comment]
from pyrate_limiter import (
ModuleNotFoundError: No module named 'pyrate_limiter'
[root@server SaitamaRobot]# pip3 install pyrate_limiter
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting pyrate_limiter
  Could not find a version that satisfies the requirement pyrate_limiter (from versions: )
No matching distribution found for pyrate_limiter
[root@server SaitamaRobot]# 

lol muje rona a gya ak ke badd ak problem

**Comment by starry-shivam** [comment]
If you even don't understand basic stuffs i don't see any point in hosting your own bot. And saitama isn't a beginner level project anyway

**Comment by starry-shivam** [comment]
just use any readymade group manager bot of your choice and live in peace
