### ISSUE TITLE
Bug report:  {mention} doesnt mention the user in filters and notes, just prints the name

### ISSUE THREAD

**Issue by TsunayoshiSawada** [AnimeKaizoku/SaitamaRobot#381]
**Describe the bug**
{mention} doesnt mention the user in filters and notes, just prints the name

**Expected behavior**
It should mention the user.

**Comment by ajhalili2006** [comment]
Either one of the following:

1. Bug on creating mention on code side
2. The forwarded message's original sender is hidden
3. User don't have username and disabled forwards are only mentionable in mutual chats and in PMs. (see https://t.me/BotTalk/157765)

**Comment by TsunayoshiSawada** [comment]
This was fixed by Veer
