### ISSUE TITLE
Bump Support to Telegram 12.x

### ISSUE THREAD

**Issue by tugapower0** [AnimeKaizoku/SaitamaRobot#41]
Its you guys planing to update support to python_telegram_bot==12.5.1 ?

Getting warnings and AttributeError errors on 12.5.1

`  super().__init__(pattern, callback, **kwargs)
/data/bots/.local/lib/python3.7/site-packages/telegram/ext/regexhandler.py:121: TelegramDeprecationWarning: message_updates is deprecated. See https://git.io/fxJuV for more info                                 
  edited_updates=edited_updates)
/data/bots/.local/lib/python3.7/site-packages/telegram/ext/regexhandler.py:121: TelegramDeprecationWarning: channel_post_updates is deprecated. See https://git.io/fxJuV for more info                            
  edited_updates=edited_updates)
/data/bots/.local/lib/python3.7/site-packages/telegram/ext/regexhandler.py:121: TelegramDeprecationWarning: edited_updates is deprecated. See https://git.io/fxJuV for more info                                  
  edited_updates=edited_updates)
/data/bots/Bob/tg_bot/modules/helper_funcs/handlers.py:56: TelegramDeprecationWarning: edited_updates is deprecated. See https://git.io/fxJuV for more info                                                       
  super().__init__(filters, callback, **kwargs)`

Thanks in advance

**Comment by DragSama** [comment]
Saitama doesn't support v12+

**Comment by DragSama** [comment]
Not right now atleast, If you free you can remake whole bot in v12

**Comment by tugapower0** [comment]
thanks
