### ISSUE TITLE
filters.py

### ISSUE THREAD

**Issue by ufoptg** [AnimeKaizoku/SaitamaRobot#410]
**I wanted to ask that...**
Just type your question here [...]
Im very sorry.

File "/home/tgbot/tgbot/SaitamaRobot/modules/remote_cmds.py", line 9, in <module>
    from SaitamaRobot.modules.helper_funcs.filters import CustomFilters
  File "/home/tgbot/tgbot/SaitamaRobot/modules/helper_funcs/filters.py", line 6, in <module>
    class CustomFilters(object):
  File "/home/tgbot/tgbot/SaitamaRobot/modules/helper_funcs/filters.py", line 11, in CustomFilters
    support_filter = _Supporters()
TypeError: Can't instantiate abstract class _Supporters with abstract methods __call__

**Comment by ufoptg** [comment]
Seems to pass without errors when i add

# to all lines simlar to this support_filter = _Supporters

And i add 
c=CustomFilters()

To the very bottom... but obviously it runs into errors later when customfilter handler cant be called

**Comment by ufoptg** [comment]
Sorry that was meant to be a hashtag

**Comment by SHRE-YANSH** [comment]
Use python-telegram-bot version 12.8.
```pip install python-telegram-bot==12.8```

**Comment by ufoptg** [comment]
That got it thank you!
