### ISSUE TITLE
disasters.py

### ISSUE THREAD

**Issue by ufoptg** [AnimeKaizoku/SaitamaRobot#422]
The disasters module isn't working properly..
When adding a user the bot doesn't return any messages or remove them from the old category.

It shows demote messages and the message if user is in the same category your trying to add it to. Also some messages showing if the user your demoting is in DRAGONS

**Comment by TsunayoshiSawada** [comment]
1. You provided no error log
2. You are probably on Heroku and the disasters module won't work well there 

And most importantly ....

3. We do not provide support on forks
