### ISSUE TITLE
welcome.py

### ISSUE THREAD

**Issue by ufoptg** [AnimeKaizoku/SaitamaRobot#423]
Could someone help every time I load welcome module I start getting these errors

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column welcome_pref.custom_content does not exist  LINE 1: ...ef.should_goodbye AS welcome_pref_should_goodbye, welcome_pr...
  ^

Which then starts a chain reaction

**Comment by TsunayoshiSawada** [comment]
Saitama provides no support for forks. 
When you fork it, its your responsibility to fix any errors you face
