### ISSUE TITLE
just noticed an error from handlers.py is this new?

### ISSUE THREAD

**Issue by ufoptg** [AnimeKaizoku/SaitamaRobot#424]
I got the following error after running bot but don't remember it before is it new or is it just because running python 12

/home/tgbot/btg/tg_bot/modules/helper_funcs/handlers.py:126: TelegramDeprecationWarning: RegexHandler is deprecated. See https://git.io/fxJuV for more info
  super().__init__(pattern, callback, **kwargs)
/home/tgbot/.local/lib/python3.7/site-packages/telegram/ext/regexhandler.py:121: TelegramDeprecationWarning: message_updates is deprecated. See https://git.io/fxJuV for more info
  edited_updates=edited_updates)
/home/tgbot/.local/lib/python3.7/site-packages/telegram/ext/regexhandler.py:121: TelegramDeprecationWarning: channel_post_updates is deprecated. See https://git.io/fxJuV for more info
  edited_updates=edited_updates)
/home/tgbot/.local/lib/python3.7/site-packages/telegram/ext/regexhandler.py:121: TelegramDeprecationWarning: edited_updates is deprecated. See https://git.io/fxJuV for more info
  edited_updates=edited_updates)

**Comment by TsunayoshiSawada** [comment]
- The path is "tgbot" the bot we have is "SaitamaRobot" in path
- Python 12 does not exist, I think you meant python-telegram-bot v12
- Saitama already uses v12.8 as shown [here](https://github.com/AnimeKaizoku/SaitamaRobot/blob/master/requirements.txt#L25)

Kindly avoid bringing some other repo queries to Saitama's.

**Comment by ufoptg** [comment]
Thats what I meant, yup sorry changed the path in my directory for testing purposes as SaitamaRobot was to long to type when editing as I do most from phone. May sound stupid but replace all function works well But okay I was only curious. . I still recieve the same warning with bot just straight cloned.

/home/tgbot/tg/SaitamaRobot/modules/helper_funcs/handlers.py:126: TelegramDeprecationWarning: RegexHandler is deprecated. See https://git.io/fxJuV for more info
  super().__init__(pattern, callback, **kwargs)

**Comment by TsunayoshiSawada** [comment]
Again 

- Saitama already uses v12.8 

So you would not be getting this error. 
Uninstall your python-telegram-bot via 
pip uninstall python-telegram-bot

Then do 
pip install -r requirements.txt
