### ISSUE TITLE
Nice bot

### ISSUE THREAD

**Issue by Colossalhavoc** [AnimeKaizoku/SaitamaRobot#90]

**Comment by TsunayoshiSawada** [comment]
>new issue
>compliment

Bruh! 
So the issue is the bot is nice?

**Comment by Colossalhavoc** [comment]
Actually the real issue is when I type in slash the drop down menu for the
commands is not showing up

**Comment by kshatriya-abhay** [comment]
It's made that way. So that if Saitama is the only bot in the group, it doesn't show that ’/' icon in the text box.

You can use /help to get commands list

**Comment by TsunayoshiSawada** [comment]
Im assuming you meant something like this
![image](https://user-images.githubusercontent.com/34431649/85645650-f68e1b00-b6b7-11ea-8b20-d56ce35a768e.png)
These are hella gay and saitama has no commands listed. 

The only command you need to know is /help which covers every other command. 
If you text the bot for the first time the ONLY command you can send is /start which is automated. 
/start lists everything from bot source code to the help command itself. 

Users tend to spam / commands if we add them to quick command list, imagine your 3000 member group and every day some random noob just taps the /help or any other command. 
welp.

**Comment by TsunayoshiSawada** [comment]
> if Saitama is the only bot in the group, it doesn't show that ’/' icon in the text box.


Well its actual reasoning is that a group management bot doesnt really need those commands listed.

**Comment by Colossalhavoc** [comment]
Thank you very much for going through the trouble of explaining a noob like
me

**Comment by Dank-del** [comment]
@TsunayoshiSawada Ignore him, he's some random nigga from my school

**Comment by Colossalhavoc** [comment]
Who said I am from your school

**Comment by Dank-del** [comment]
@Collosalhavoc Dattatreyo ok

**Comment by Colossalhavoc** [comment]
😏

**Comment by TsunayoshiSawada** [comment]
I literally closed this issue.
Does GitHub not give a fuck what a closed topic is?

**Comment by Colossalhavoc** [comment]
> I literally closed this issue.
> Does GitHub not give a fuck what a closed topic is? 

GitHub is gey
